### ISSUE TITLE
State of code, potential contributions and Rust API?

### ISSUE THREAD

**Issue by nyanpasu64** [edgeone89/pocketfft_rust#1]
I'm considering using pocketfft for my own Rust projects (via Cargo, not through precompiled library linking). What's the state of this code?

- Is it production-ready and/or used in your projects right now?
- It seems it's currently configured as a shared/static library with C API, that may be ABI-compatible with the original pocketfft. Is there a Rust API wrapper, and should I port it to an idiomatic-Rust API or not?
- If I write a Rust wrapper, what should the C API and Rust wrapper crates be named? Alternatively, what if I port to a Rust API and write a C wrapper?
- The library is not on crates.io. The [crate guidelines](https://rust-lang.github.io/api-guidelines/naming.html) say not to name crates `-rust`, so this would be called `pocketfft`. I don't know what the shared/static library would be called in that case.
- Do you have test cases (like the simple original pocketfft test program at https://gitlab.mpcdf.mpg.de/mtr/pocketfft/-/blob/master/ffttest.c)?
- Are there benchmarks to compare the C and Rust versions' speed?

## Background

rustfft is slow at prime lengths, and the realfft helper crate only supports even-length inputs. pocketfft seems like a fairly reasonable and full-featured library, with both real and complex inputs supported for all lengths, Bluestein's algorithm for efficient prime-length transforms, and it's used in NumPy.

I've noticed that this repository is not very popular, and not idiomatic Rust:

- raw pointers instead of Box
- manual deletion functions instead of relying on Box's drop glue
- no methods, no impl blocks
- 16 unsafe instances (I don't know how bad this is, without reading more deeply)

**Comment by nyanpasu64** [comment]
I decided to clone this repo and step through the warnings. I'm noticing a lot of todo comments and commented-out code, that makes me feel less than confident that this works well.

- `fn PMC` etc. is unused. It was a macro in the C code. You could turn it into a `macro_rules` (Rust's interim solution for macros until Macros 2.0 is finished).
- `pub type cfftp_plan = *mut cfftp_plan_i;` where `cfftp_plan_i` is not `pub` is a warning, and will be an error in a future Rust compiler version.
- In `pass_all`, `fct` is unused while it was used in the original C code. There's fragmentary commented-out code in the Rust port. I don't know if there's any other incomplete/messy code in the port, that I didn't notice yet.
- `cfftp_twsize` is not used, and `make_cfftp_plan` has a commented call to the function.
- `cfftp_comp_twiddle` has an `memofs` variable only read in commented code.
- `fftblue_plan_i::mem` is not read.
- `let mut` is not necessary if a variable is assigned once.

There were a few other warnings, I didn't list everything.

----

Just noticed that the entire library is hard-coded as f64, even though offering a f32 version would be somewhat faster, and accurate enough for audio (though I don't know if it would produce unacceptable internal errors during the FFT process).

----

- Why is `make_cfft_plan` an unsafe fn? Raw pointers are safe to create.
- Maybe `destroy_cfftp_plan` should be `unsafe fn`, because `cfftp_plan = *mut cfftp_plan_i` (a type alias) could be invalid. It's less of a pressing concern because the function is not public, but I still feel it's `unsafe` because it can directly lead to memory unsafety (not just break invariants).
  - Same with `destroy_fftblue_plan`.

**Comment by nyanpasu64** [comment]
I ported over the pocketfft test cases, and I'm getting incorrect results, Vec panics, and segfaults left and right.

**Comment by egdeeno** [comment]
Hello!
the lib is early alpha, so there is a lot to do.

**Comment by egdeeno** [comment]
first things first is to make the lib work correctly;
then to get rid of commented code and unsafe blocks as much as possible, but C api functions will be unsafe(those marked 'unsafe' intentionally);
then to optimize it and make it fast;

suggestions and pull-requests are appreciated
